model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 15
    feature_size: 1
    n_layer_enc: 2
    n_layer_dec: 2
    d_model: 64  # 4 X 16
    timesteps: 500
    sampling_timesteps: 500
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.05
    resid_pd: 0.05
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-5
  max_epochs: 10000
  results_folder: ./Checkpoints/Checkpoints_data2_Ours_x_y_a_short
  gradient_accumulate_every: 2
  save_cycle: 1000  # max_epochs // 10
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 2000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: Utils.Data_utils.real_datasets.CustomDatasetTrain
    params:
      name: data1_DiffPO_y
      proportion: 1.0  # Set to rate < 1 if training conditional generation
      data_root: ./Data/datasets/data2_react/data2_train_y.csv
      window: 15  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train

  test_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: data1_DiffPO_y
      proportion: 1.0  # rate
      data_root: ./Data/datasets/data2_react/hybrid_train.csv
      window: 45  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train
    
  sample_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: data1_DiffPO_y
      proportion: 1.0  # rate
      data_root: ./Data/datasets/data2_react/hybrid_test.csv
      window: 45  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train
    
  gt_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: data1_DiffPO_y
      proportion: 1.0  # rate
      data_root: ./Data/datasets/data2_react/data2_train_y_norm.csv
      window: 15  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train
  
  expf_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: data1_DiffPO_y
      proportion: 1.0  # rate
      data_root: ./Data/datasets/data2_react/expert_y_f_norm_new.csv
      window: 15  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train
  
  expc_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: data1_DiffPO_y
      proportion: 1.0  # rate
      data_root: ./Data/datasets/data2_react/expert_y_c_norm_new.csv
      window: 15  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train
  
  
  
  weight_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: data1_DiffPO_y
      proportion: 1.0  # rate
      data_root: ./Data/datasets/dataset2_final/data2_weights_short.csv
      window: 1  # seq_length
      save2npy: True
      neg_one_to_one: False
      seed: 123
      period: train

  batch_size: 32
  sample_size: 150
  shuffle: False